DEVELOPMENT_ADDRESS = '127.0.0.1'

DEPLOYMENT_ADDRESS = '3.24.141.26'

DEPLOY = True

SERVER_ADDRESS = DEPLOYMENT_ADDRESS if DEPLOY else DEVELOPMENT_ADDRESS

TARGET_JOB_PRIORITIES = ['high', 'default', 'low']

DB_ADDRESS = 'mongodb://' + SERVER_ADDRESS + ':27017/'

DB_USERNAME = 'hyperlynk'

DB_PASSWORD = 'OnePurpleParrot'

REDIS_ADDRESS = SERVER_ADDRESS

REDIS_PORT = 6379

PULSAR_ADDRESS = 'pulsar://' + SERVER_ADDRESS + ':6650'