version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: BackendDB
    ports:
      - 8000:3306
    expose:
      - 8000

  web:
    build: ./backend
    ports:
      - 8001:8080
    expose:
      - 8001
    links:
      - db
