version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: BackendDB

  back:
    build: ./backend
    ports:
      - 8000:8000
    expose:
      - 8000
    links:
      - db

  front:
    build: ./frontend
    ports:
      - 3000:80
    expose:
      - 3000
