DEVELOPMENT_ADDRESS = "192.168.1.9"

DEPLOYMENT_ADDRESS = "3.24.141.26"

DEPLOY = False

SERVER_ADDRESS = DEPLOYMENT_ADDRESS if DEPLOY else DEVELOPMENT_ADDRESS

SERVER_PORT = 6379

TARGET_JOB_PRIORITIES = ['high', 'default', 'low']